# Generated by Django 5.2.17 on 2026-08-26 08:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when updated')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when soft-deleted', null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete status flag')),
                ('code', models.CharField(help_text='Unique module code e.g. FUND_RECEIPTS', max_length=50, unique=True)),
                ('name', models.CharField(help_text='Menu display name e.g. Funds Received', max_length=100)),
                ('url', models.CharField(help_text='Navigation URL matching config URLs e.g. /funds/', max_length=200)),
                ('icon_class', models.CharField(default='bi-folder', help_text='Bootstrap icon class', max_length=50)),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('available_rights', models.JSONField(default=list, help_text='List of right codes supported by module (add, edit, delete_single, delete_bulk, print_single, print_bulk)')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created the record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, help_text='User who soft-deleted the record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, help_text='Parent module for multi-level navigation tree', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='administration.appmodule')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated the record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'administration_app_module',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when updated')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when soft-deleted', null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete status flag')),
                ('assigned_rights', models.JSONField(default=list, help_text='List of assigned right codes for this role and module')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created the record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, help_text='User who soft-deleted the record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='administration.appmodule')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='administration.lookupvalue')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated the record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'administration_role_permission',
                'unique_together': {('role', 'module')},
            },
        ),
    ]
