# Generated by Django 5.2.17 on 2026-08-25 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensevoucher',
            name='expense_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='expensevoucher',
            name='status',
            field=models.CharField(db_index=True, default='Approved', max_length=50),
        ),
        migrations.AlterField(
            model_name='expensevoucher',
            name='voucher_number',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
    ]
