# Generated by Django 5.2.17 on 2026-08-25 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundreceipt',
            name='date_received',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='fundreceipt',
            name='donor_phone',
            field=models.CharField(blank=True, db_index=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='fundreceipt',
            name='receipt_number',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
    ]
