# Generated by Django 5.2.17 on 2026-08-25 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='auditlog',
            table='audit_auditlog',
        ),
    ]
