# Generated by Django 5.2.17 on 2026-08-25 08:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_alter_auditlog_table'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_name', models.CharField(blank=True, default='', max_length=150)),
                ('recipient_phone', models.CharField(max_length=20)),
                ('channel', models.CharField(choices=[('WHATSAPP', 'WhatsApp'), ('SMS', 'SMS'), ('EMAIL', 'Email'), ('OTP', 'OTP Code')], default='WHATSAPP', max_length=20)),
                ('purpose', models.CharField(help_text='e.g. DONATION_RECEIPT, MFA_OTP, PASSWORD_RESET, HIGH_VALUE_ALERT', max_length=100)),
                ('message_body', models.TextField()),
                ('dispatch_url', models.URLField(blank=True, default='', max_length=1000)),
                ('status', models.CharField(choices=[('SENT', 'Sent'), ('DELIVERED', 'Delivered'), ('FAILED', 'Failed'), ('PENDING', 'Pending')], default='SENT', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_notificationlog',
                'ordering': ['-timestamp'],
            },
        ),
    ]
