# Generated by Django 5.2.17 on 2026-08-25 06:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(db_index=True, max_length=100)),
                ('test_name', models.CharField(max_length=255, unique=True)),
                ('severity', models.CharField(default='HIGH', max_length=20)),
                ('status', models.CharField(default='OPEN', max_length=20)),
                ('failure_count', models.IntegerField(default=1)),
                ('first_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('latest_error', models.TextField(blank=True, null=True)),
                ('branch', models.CharField(default='main', max_length=100)),
                ('commit_hash', models.CharField(default='a82f91c', max_length=40)),
            ],
            options={
                'db_table': 'qa_test_issue',
                'ordering': ['-severity', '-last_seen'],
            },
        ),
        migrations.CreateModel(
            name='TestRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('branch', models.CharField(default='main', max_length=100)),
                ('commit_hash', models.CharField(default='a82f91c', max_length=40)),
                ('application_version', models.CharField(default='v2.4', max_length=50)),
                ('total_tests', models.IntegerField(default=0)),
                ('passed', models.IntegerField(default=0)),
                ('failed', models.IntegerField(default=0)),
                ('skipped', models.IntegerField(default=0)),
                ('pass_rate', models.FloatField(default=0.0)),
                ('duration_seconds', models.FloatField(default=0.0)),
            ],
            options={
                'db_table': 'qa_test_run',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(db_index=True, max_length=100)),
                ('test_name', models.CharField(max_length=255)),
                ('test_status', models.CharField(default='PASSED', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('severity', models.CharField(default='MEDIUM', max_length=20)),
                ('duration_ms', models.FloatField(default=0.0)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='qa_dashboard.testrun')),
            ],
            options={
                'db_table': 'qa_test_result',
                'ordering': ['module', 'test_name'],
            },
        ),
    ]
