# Generated by Django 6.1 on 2026-08-21 07:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when updated')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when soft-deleted', null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete status flag')),
                ('member_id', models.CharField(help_text='e.g. MBR-2026-001', max_length=50, unique=True)),
                ('full_name', models.CharField(max_length=150)),
                ('mobile_number', models.CharField(max_length=15)),
                ('committee_position', models.CharField(help_text='e.g. Chief Treasurer, President', max_length=100)),
                ('system_role', models.CharField(default='Committee Member', max_length=100)),
                ('joining_date', models.DateField()),
                ('status', models.CharField(default='Active', max_length=20)),
                ('address', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created the record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, help_text='User who soft-deleted the record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated the record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'members_member',
                'ordering': ['member_id'],
            },
        ),
    ]
